
site_name: ZonePlus
site_description: Documentation for ZonePlus
site_author: Ben Horton
site_url: https://1ForeverHD.github.io/ZonePlus/

repo_name: 1ForeverHD/ZonePlus
repo_url: https://github.com/1ForeverHD/ZonePlus
edit_uri: ""

theme:
  logo: https://user-images.githubusercontent.com/51117782/104590568-71724f80-5663-11eb-9bc1-344fc2a4193c.png
  favicon: https://user-images.githubusercontent.com/51117782/113474423-cefa8900-9467-11eb-8678-d69cbb0b3966.png
  name: material
  features:
    - navigation.tabs
    #- navigation.instant
    #- navigation.sections
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  highlightjs: true
  hljs_languages:
    - lua

extra_javascript:
  - javascripts/tags.js

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/1ForeverHD/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ForeverHD_
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCj9QhyYCvhAwiBHA5B88pYg

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences

nav:
  - Home:
    - Introduction: index.md
    - Examples: examples.md
    - Installation: installation.md
    - Method: method.md
    - API:
      - Zone: api/zone.md
      - ZoneController: api/zone_controller.md
    - Resources: resources.md
  - Contributing: contributing.md
  - Changelog: changelog.md